name: Publish

on:
  push:
    tags:
      - "v*.*.*"   # e.g. v1.2.3

jobs:
  # Reuse the test workflow
  test:
    uses: ./.github/workflows/test.yml

  publish:
    name: Publish to npm
    needs: [test]   # ensure tests run first
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: "https://registry.npmjs.org"

      - name: Install root deps
        run: npm ci

      - name: Build package
        run: npm run build --if-present

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
